# Email Sittings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_FROM = 'ENTER YOUR EMAIL ADDRESS'
EMAIL_HOST_USER = 'ENTER YOUR EMAIL ADDRESS'
EMAIL_HOST_PASSWORD = 'ENTER YOUR PASSWORD'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
PASSWORD_RESET_TIMEOUT = 86400


# database config

DATA_BASE_USER_NAME = 'ENTER YOUR DATABASE USER NAME'
DB_NAME = 'ENTER YOUR DATABASE NAME'
DB_PASSWORD = 'ENTER DATABASE PASSWORD'
DB_HOST = 'YOUR LOCAL HOST AKA 127.0.0.1'
DB_PORT = '5432'